Dev
uofu-emb/lab3_phelan_thomas pull request #1
Opened 2024-10-17 03:25 UTC by thomasjw99

2024-10-18 21:59 UTC, VarunBhavya requested changes
I have added my queries and thoughts regarding the issues in two files. If you believe I have misunderstood anything, please let me know. I am open to clarifying my understanding and will approve the pull request once any concerns are addressed.

2024-10-18 21:59 UTC, VarunBhavya commented on src/threadfunc.c
I have a question about lines 72-76. While I recognize that pdFALSE is returned for failed operations, I don't see its necessity in this condition. Could you please explain why you've included it here? Are you considering the if statement to be a failed operation?

2024-10-18 21:59 UTC, VarunBhavya commented on test/test.c
An unorphaned lock should address the issue with the orphaned lock. However, we are verifying for a failed operation in the unorphaned lock function. Could you let me know if you are certain the test is passing? In line 117, you should compare it with 1, as done in line 112.

Also, in the orphaned lock function, lines 90-94 and 96-100 seem to perform the same operation. Is there any particular reason for this?

2024-10-30 19:11 UTC, thomasjw99 commented on src/threadfunc.c
I have updated it to return 0. You were right about the return pdFalse as it is a logic error not a system error where the semaphore is taken.

2024-10-30 19:12 UTC, thomasjw99 commented on test/test.c
As we discussed, I have made the comment on the redundant test.

2024-11-03 00:32 UTC, VarunBhavya commented
All the changes have been successfully implemented, and everything looks good to me!

2024-11-03 00:33 UTC, VarunBhavya approved these changes
Looks good and I approve the pull request.

2024-11-21 15:20 UTC, merged